name: build

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [main]
    workflow_dispatch:

env:
    SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}

jobs:
    notify_start:
        runs-on: ubuntu-latest
        # Ideally this condition would be promoted to a workflow-level environment variable and shared
        # but this doesn't seem to be supported yet https://github.community/t/how-to-set-and-access-a-workflow-variable/17335/6
        if: github.repository_owner == 'AndcultureCode'
        steps:
            - uses: voxmedia/github-action-slack-notify-build@v1
              if: env.SLACK_BOT_TOKEN != ''
              with:
                  channel: company-andculture-code-ci
                  color: "#3278BD"
                  status: STARTED
    build:
        runs-on: windows-latest
        needs: [notify_start]
        if: always()

        steps:
            - uses: actions/checkout@v2

            - name: Setup node 8.16.2
              uses: actions/setup-node@v2
              with:
                  node-version: 8.16.2

            - name: npm install
              run: |
                  npm install

            - name: Install plugin-cli globally
              run: |
                  npm install -g .

            - name: Smoke test
              run: |
                  plugin-cli
                  plugin-cli example
                  plugin-cli ex

    notify_success:
        runs-on: ubuntu-latest
        needs: [build]
        if: github.repository_owner == 'AndcultureCode' && success()
        steps:
            - uses: voxmedia/github-action-slack-notify-build@v1
              if: env.SLACK_BOT_TOKEN != ''
              with:
                  channel: company-andculture-code-ci
                  color: good
                  status: SUCCESS

    notify_failure:
        runs-on: ubuntu-latest
        needs: [build]
        if: github.repository_owner == 'AndcultureCode' && failure()
        steps:
            - uses: voxmedia/github-action-slack-notify-build@v1
              if: env.SLACK_BOT_TOKEN != ''
              with:
                  channel: company-andculture-code-ci
                  color: danger
                  status: FAILED
